version: '3'

services:
  app:
    build:
      context: .docker.local/app
    ports:
      - 22040:80
    volumes:
      - ./:/var/www/html
      - ./.docker.local/app/logs/nginx:/var/log/nginx
      - ./.docker.local/app/.composer:/root/.composer
    depends_on:
      - postgres

  postgres:
    build:
      context: .docker.local/postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./.docker.local/postgres/data:/var/lib/postgresql/data
    ports:
      - 22041:${DB_PORT}
